[package]
name = "trit"
version = "0.0.1"
edition = "2021"
description = "A library for working with trinary bits and bit strings."
license = "none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
